? CPU24
MF FUNCCALC_CPU24 1
M FC_TARGET_ENTER @PUSH 1 @SSET SegDS @PUSH 1 @ADM
M FC_TARGET_EXIT @PUSH 0 @ADM
M FC_TARGET_HEAP_INIT @PUSH __DEND @PUSH 0xf800 @SUB __DEND
.DATA 1
I commonDS.mc
ENDBLOCK
! CPU24
M FC_TARGET_ENTER
M FC_TARGET_EXIT
M FC_TARGET_HEAP_INIT @PUSH END__ @PUSH 0xf800 @SUB END__
I common.mc
ENDBLOCK
I FuncCalcCore.asm
