:Var_Neg1   -1
:Var_Zero    0
:Var_One     1
:Var_Two     2
:Var_Five    5
:Var_HighBit 0x8000
:Var_Large   0x7FFF

# Auto-generated IF test suite (16-bit)
I common.mc
@PRTNL
@PRT "BEGIN IF TESTS" @PRTNL
:Main . Main
@JMP StartTest
# === TEST IF_NEG ===
@PUSH 0 @SUB 1
@IF_NEG
  @PRT "PASS IF_NEG true" @PRTNL
@ELSE
  @PRT "FAIL IF_NEG true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1 @SUB 0
@IF_NEG
  @PRT "FAIL IF_NEG false" @PRTNL
@ELSE
  @PRT "PASS IF_NEG false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_POS ===
@PUSH 1 @SUB 0
@IF_POS
  @PRT "PASS IF_POS true" @PRTNL
@ELSE
  @PRT "FAIL IF_POS true" @PRTNL
@ENDIF
@POPNULL

@PUSH 0 @SUB 1
@IF_POS
  @PRT "FAIL IF_POS false" @PRTNL
@ELSE
  @PRT "PASS IF_POS false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_OVERFLOW ===
@PUSH 0x7FFF @ADD 1
@IF_OVERFLOW
  @PRT "PASS IF_OVERFLOW true" @PRTNL
@ELSE
  @PRT "FAIL IF_OVERFLOW true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1 @ADD 1
@IF_OVERFLOW
  @PRT "FAIL IF_OVERFLOW false" @PRTNL
@ELSE
  @PRT "PASS IF_OVERFLOW false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_NOTOVER ===
@PUSH 1 @ADD 1
@IF_NOTOVER
  @PRT "PASS IF_NOTOVER true" @PRTNL
@ELSE
  @PRT "FAIL IF_NOTOVER true" @PRTNL
@ENDIF
@POPNULL

@PUSH 0x7FFF @ADD 1
@IF_NOTOVER
  @PRT "FAIL IF_NOTOVER false" @PRTNL
@ELSE
  @PRT "PASS IF_NOTOVER false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_CARRY ===
@PUSH 0xFFFF @ADD 1
@IF_CARRY
  @PRT "PASS IF_CARRY true" @PRTNL
@ELSE
  @PRT "FAIL IF_CARRY true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1 @ADD 1
@IF_CARRY
  @PRT "FAIL IF_CARRY false" @PRTNL
@ELSE
  @PRT "PASS IF_CARRY false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_NOTCARRY ===
@PUSH 1 @ADD 1
@IF_NOTCARRY
  @PRT "PASS IF_NOTCARRY true" @PRTNL
@ELSE
  @PRT "FAIL IF_NOTCARRY true" @PRTNL
@ENDIF
@POPNULL

@PUSH 0xFFFF @ADD 1
@IF_NOTCARRY
  @PRT "FAIL IF_NOTCARRY false" @PRTNL
@ELSE
  @PRT "PASS IF_NOTCARRY false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_ZFLAG ===
@PUSH 1 @SUB 1
@IF_ZFLAG
  @PRT "PASS IF_ZFLAG true" @PRTNL
@ELSE
  @PRT "FAIL IF_ZFLAG true" @PRTNL
@ENDIF
@POPNULL

@PUSH 2 @SUB 1
@IF_ZFLAG
  @PRT "FAIL IF_ZFLAG false" @PRTNL
@ELSE
  @PRT "PASS IF_ZFLAG false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_NOTZF ===
@PUSH 2 @SUB 1
@IF_NOTZF
  @PRT "PASS IF_NOTZF true" @PRTNL
@ELSE
  @PRT "FAIL IF_NOTZF true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1 @SUB 1
@IF_NOTZF
  @PRT "FAIL IF_NOTZF false" @PRTNL
@ELSE
  @PRT "PASS IF_NOTZF false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_ZERO ===
@PUSH 1 @SUB 1
@IF_ZERO
  @PRT "PASS IF_ZERO true" @PRTNL
@ELSE
  @PRT "FAIL IF_ZERO true" @PRTNL
@ENDIF
@POPNULL

@PUSH 2 @SUB 1
@IF_ZERO
  @PRT "FAIL IF_ZERO false" @PRTNL
@ELSE
  @PRT "PASS IF_ZERO false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_NOTZERO ===
@PUSH 2 @SUB 1
@IF_NOTZERO
  @PRT "PASS IF_NOTZERO true" @PRTNL
@ELSE
  @PRT "FAIL IF_NOTZERO true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1 @SUB 1
@IF_NOTZERO
  @PRT "FAIL IF_NOTZERO false" @PRTNL
@ELSE
  @PRT "PASS IF_NOTZERO false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_EQ_S ===
@PUSH 1 @PUSH 1
@IF_EQ_S
  @PRT "PASS IF_EQ_S true" @PRTNL
@ELSE
  @PRT "FAIL IF_EQ_S true" @PRTNL
@ENDIF
@POPNULL @POPNULL

@PUSH 1 @PUSH 2
@IF_EQ_S
  @PRT "FAIL IF_EQ_S false" @PRTNL
@ELSE
  @PRT "PASS IF_EQ_S false" @PRTNL
@ENDIF
@POPNULL @POPNULL


# === TEST IF_EQ_A ===
@PUSH 1
@IF_EQ_A 1
  @PRT "PASS IF_EQ_A true" @PRTNL
@ELSE
  @PRT "FAIL IF_EQ_A true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_EQ_A 2
  @PRT "FAIL IF_EQ_A false" @PRTNL
@ELSE
  @PRT "PASS IF_EQ_A false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_EQ_V ===
@PUSH 1
@IF_EQ_V Var_One
  @PRT "PASS IF_EQ_V true" @PRTNL
@ELSE
  @PRT "FAIL IF_EQ_V true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_EQ_V Var_Two
  @PRT "FAIL IF_EQ_V false" @PRTNL
@ELSE
  @PRT "PASS IF_EQ_V false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_NEQ_S ===
@PUSH 1 @PUSH 2
@IF_NEQ_S
  @PRT "PASS IF_NEQ_S true" @PRTNL
@ELSE
  @PRT "FAIL IF_NEQ_S true" @PRTNL
@ENDIF
@POPNULL @POPNULL

@PUSH 1 @PUSH 1
@IF_NEQ_S
  @PRT "FAIL IF_NEQ_S false" @PRTNL
@ELSE
  @PRT "PASS IF_NEQ_S false" @PRTNL
@ENDIF
@POPNULL @POPNULL


# === TEST IF_NEQ_A ===
@PUSH 1
@IF_NEQ_A 2
  @PRT "PASS IF_NEQ_A true" @PRTNL
@ELSE
  @PRT "FAIL IF_NEQ_A true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_NEQ_A 1
  @PRT "FAIL IF_NEQ_A false" @PRTNL
@ELSE
  @PRT "PASS IF_NEQ_A false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_NEQ_V ===
@PUSH 1
@IF_NEQ_V Var_Two
  @PRT "PASS IF_NEQ_V true" @PRTNL
@ELSE
  @PRT "FAIL IF_NEQ_V true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_NEQ_V Var_One
  @PRT "FAIL IF_NEQ_V false" @PRTNL
@ELSE
  @PRT "PASS IF_NEQ_V false" @PRTNL
@ENDIF
@POPNULL

# === TEST IF_LT_S ===
@PUSH 1 @PUSH 2
@IF_LT_S
  @PRT "PASS IF_LT_S true" @PRTNL
@ELSE
  @PRT "FAIL IF_LT_S true" @PRTNL
@ENDIF
@POPNULL @POPNULL

@PUSH 2 @PUSH 1
@IF_LT_S
  @PRT "FAIL IF_LT_S false" @PRTNL
@ELSE
  @PRT "PASS IF_LT_S false" @PRTNL
@ENDIF
@POPNULL @POPNULL


# === TEST IF_LT_A ===
@PUSH 1
@IF_LT_A 2
  @PRT "PASS IF_LT_A true" @PRTNL
@ELSE
  @PRT "FAIL IF_LT_A true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_LT_A 1
  @PRT "FAIL IF_LT_A false" @PRTNL
@ELSE
  @PRT "PASS IF_LT_A false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_LT_V ===
@PUSH 1
@IF_LT_V Var_Two
  @PRT "PASS IF_LT_V true" @PRTNL
@ELSE
  @PRT "FAIL IF_LT_V true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_LT_V Var_One
  @PRT "FAIL IF_LT_V false" @PRTNL
@ELSE
  @PRT "PASS IF_LT_V false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_LE_S ===
@PUSH 1 @PUSH 2
@IF_LE_S
  @PRT "PASS IF_LE_S true" @PRTNL
@ELSE
  @PRT "FAIL IF_LE_S true" @PRTNL
@ENDIF
@POPNULL @POPNULL

@PUSH 2 @PUSH 1
@IF_LE_S
  @PRT "FAIL IF_LE_S false" @PRTNL
@ELSE
  @PRT "PASS IF_LE_S false" @PRTNL
@ENDIF
@POPNULL @POPNULL


# === TEST IF_LE_A ===
@PUSH 1
@IF_LE_A 2
  @PRT "PASS IF_LE_A true" @PRTNL
@ELSE
  @PRT "FAIL IF_LE_A true" @PRTNL
@ENDIF
@POPNULL

@PUSH 2
@IF_LE_A 1
  @PRT "FAIL IF_LE_A false" @PRTNL
@ELSE
  @PRT "PASS IF_LE_A false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_LE_V ===
@PUSH 1
@IF_LE_V Var_Two
  @PRT "PASS IF_LE_V true" @PRTNL
@ELSE
  @PRT "FAIL IF_LE_V true" @PRTNL
@ENDIF
@POPNULL

@PUSH 2
@IF_LE_V Var_One
  @PRT "FAIL IF_LE_V false" @PRTNL
@ELSE
  @PRT "PASS IF_LE_V false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_GE_S ===
@PUSH 2 @PUSH 1
@IF_GE_S
  @PRT "PASS IF_GE_S true" @PRTNL
@ELSE
  @PRT "FAIL IF_GE_S true" @PRTNL
@ENDIF
@POPNULL @POPNULL

@PUSH 1 @PUSH 2
@IF_GE_S
  @PRT "FAIL IF_GE_S false" @PRTNL
@ELSE
  @PRT "PASS IF_GE_S false" @PRTNL
@ENDIF
@POPNULL @POPNULL


# === TEST IF_GE_A ===
@PUSH 2
@IF_GE_A 1
  @PRT "PASS IF_GE_A true" @PRTNL
@ELSE
  @PRT "FAIL IF_GE_A true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_GE_A 2
  @PRT "FAIL IF_GE_A false" @PRTNL
@ELSE
  @PRT "PASS IF_GE_A false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_GE_V ===
@PUSH 2
@IF_GE_V Var_One
  @PRT "PASS IF_GE_V true" @PRTNL
@ELSE
  @PRT "FAIL IF_GE_V true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_GE_V Var_Two
  @PRT "FAIL IF_GE_V false" @PRTNL
@ELSE
  @PRT "PASS IF_GE_V false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_GT_S ===
@PUSH 2 @PUSH 1
@IF_GT_S
  @PRT "PASS IF_GT_S true" @PRTNL
@ELSE
  @PRT "FAIL IF_GT_S true" @PRTNL
@ENDIF
@POPNULL @POPNULL

@PUSH 1 @PUSH 2
@IF_GT_S
  @PRT "FAIL IF_GT_S false" @PRTNL
@ELSE
  @PRT "PASS IF_GT_S false" @PRTNL
@ENDIF
@POPNULL @POPNULL


# === TEST IF_GT_A ===
@PUSH 2
@IF_GT_A 1
  @PRT "PASS IF_GT_A true" @PRTNL
@ELSE
  @PRT "FAIL IF_GT_A true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_GT_A 1
  @PRT "FAIL IF_GT_A false" @PRTNL
@ELSE
  @PRT "PASS IF_GT_A false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_GT_V ===
@PUSH 2
@IF_GT_V Var_One
  @PRT "PASS IF_GT_V true" @PRTNL
@ELSE
  @PRT "FAIL IF_GT_V true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_GT_V Var_One
  @PRT "FAIL IF_GT_V false" @PRTNL
@ELSE
  @PRT "PASS IF_GT_V false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_ULT_S ===
@PUSH 1 @PUSH 2
@IF_ULT_S
  @PRT "PASS IF_ULT_S true" @PRTNL
@ELSE
  @PRT "FAIL IF_ULT_S true" @PRTNL
@ENDIF
@POPNULL @POPNULL

@PUSH 2 @PUSH 1
@IF_ULT_S
  @PRT "FAIL IF_ULT_S false" @PRTNL
@ELSE
  @PRT "PASS IF_ULT_S false" @PRTNL
@ENDIF
@POPNULL @POPNULL


# === TEST IF_ULT_A ===
@PUSH 1
@IF_ULT_A 2
  @PRT "PASS IF_ULT_A true" @PRTNL
@ELSE
  @PRT "FAIL IF_ULT_A true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_ULT_A 1
  @PRT "FAIL IF_ULT_A false" @PRTNL
@ELSE
  @PRT "PASS IF_ULT_A false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_ULT_V ===
@PUSH 1
@IF_ULT_V Var_Two
  @PRT "PASS IF_ULT_V true" @PRTNL
@ELSE
  @PRT "FAIL IF_ULT_V true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_ULT_V Var_One
  @PRT "FAIL IF_ULT_V false" @PRTNL
@ELSE
  @PRT "PASS IF_ULT_V false" @PRTNL
@ENDIF
@POPNULL

:StartTest
# === TEST IF_ULE_S ===
@PUSH 1 @PUSH 2
@IF_ULE_S
  @PRT "PASS IF_ULE_S true" @PRTNL
@ELSE
  @PRT "FAIL IF_ULE_S true" @PRTNL
@ENDIF
@POPNULL @POPNULL

@PUSH 2 @PUSH 1
@IF_ULE_S
  @PRT "FAIL IF_ULE_S false" @PRTNL
@ELSE
  @PRT "PASS IF_ULE_S false" @PRTNL
@ENDIF
@POPNULL @POPNULL


# === TEST IF_ULE_A ===
@PUSH 1
@IF_ULE_A 2
  @PRT "PASS IF_ULE_A true" @PRTNL
@ELSE
  @PRT "FAIL IF_ULE_A true" @PRTNL
@ENDIF
@POPNULL

@PUSH 2
@IF_ULE_A 1
  @PRT "FAIL IF_ULE_A false" @PRTNL
@ELSE
  @PRT "PASS IF_ULE_A false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_ULE_V ===
@PUSH 1
@IF_ULE_V Var_Two
  @PRT "PASS IF_ULE_V true" @PRTNL
@ELSE
  @PRT "FAIL IF_ULE_V true" @PRTNL
@ENDIF
@POPNULL

@PUSH 2
@IF_ULE_V Var_One
  @PRT "FAIL IF_ULE_V false" @PRTNL
@ELSE
  @PRT "PASS IF_ULE_V false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_UGE_S ===
@PUSH 2 @PUSH 1
@IF_UGE_S
  @PRT "PASS IF_UGE_S true" @PRTNL
@ELSE
  @PRT "FAIL IF_UGE_S true" @PRTNL
@ENDIF
@POPNULL @POPNULL

@PUSH 1 @PUSH 2
@IF_UGE_S
  @PRT "FAIL IF_UGE_S false" @PRTNL
@ELSE
  @PRT "PASS IF_UGE_S false" @PRTNL
@ENDIF
@POPNULL @POPNULL


# === TEST IF_UGE_A ===
@PUSH 2
@IF_UGE_A 1
  @PRT "PASS IF_UGE_A true" @PRTNL
@ELSE
  @PRT "FAIL IF_UGE_A true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_UGE_A 2
  @PRT "FAIL IF_UGE_A false" @PRTNL
@ELSE
  @PRT "PASS IF_UGE_A false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_UGE_V ===
@PUSH 2
@IF_UGE_V Var_One
  @PRT "PASS IF_UGE_V true" @PRTNL
@ELSE
  @PRT "FAIL IF_UGE_V true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_UGE_V Var_Two
  @PRT "FAIL IF_UGE_V false" @PRTNL
@ELSE
  @PRT "PASS IF_UGE_V false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_UGT_S ===
@PUSH 2 @PUSH 1
@IF_UGT_S
  @PRT "PASS IF_UGT_S true" @PRTNL
@ELSE
  @PRT "FAIL IF_UGT_S true" @PRTNL
@ENDIF
@POPNULL @POPNULL

@PUSH 1 @PUSH 2
@IF_UGT_S
  @PRT "FAIL IF_UGT_S false" @PRTNL
@ELSE
  @PRT "PASS IF_UGT_S false" @PRTNL
@ENDIF
@POPNULL @POPNULL


# === TEST IF_UGT_A ===
@PUSH 2
@IF_UGT_A 1
  @PRT "PASS IF_UGT_A true" @PRTNL
@ELSE
  @PRT "FAIL IF_UGT_A true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_UGT_A 1
  @PRT "FAIL IF_UGT_A false" @PRTNL
@ELSE
  @PRT "PASS IF_UGT_A false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_UGT_V ===
@PUSH 2
@IF_UGT_V Var_One
  @PRT "PASS IF_UGT_V true" @PRTNL
@ELSE
  @PRT "FAIL IF_UGT_V true" @PRTNL
@ENDIF
@POPNULL

@PUSH 1
@IF_UGT_V Var_One
  @PRT "FAIL IF_UGT_V false" @PRTNL
@ELSE
  @PRT "PASS IF_UGT_V false" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_INRANGE_AB ===
@PUSHI Var_Five
@IF_INRANGE_AB 2 10
  @PRT "PASS IF_INRANGE_AB true" @PRTNL
@ELSE
  @PRT "FAIL IF_INRANGE_AB true" @PRTNL
@ENDIF
@POPNULL

@PUSHI 15
@IF_INRANGE_AB 2 10
  @PRT "FAIL IF_INRANGE_AB false (above)" @PRTNL
@ELSE
  @PRT "PASS IF_INRANGE_AB false (above)" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_INRANGE_AV ===
@PUSHI Var_Five
@IF_INRANGE_AV 2 Var_Large
  @PRT "PASS IF_INRANGE_AV true" @PRTNL
@ELSE
  @PRT "FAIL IF_INRANGE_AV true" @PRTNL
@ENDIF
@POPNULL

@PUSHI 15
@IF_INRANGE_AV 2 Var_Large
  @PRT "FAIL IF_INRANGE_AV false (above)" @PRTNL
@ELSE
  @PRT "PASS IF_INRANGE_AV false (above)" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_INRANGE_VA ===
@PUSHI Var_Five
@IF_INRANGE_VA Var_One 10
  @PRT "PASS IF_INRANGE_VA true" @PRTNL
@ELSE
  @PRT "FAIL IF_INRANGE_VA true" @PRTNL
@ENDIF
@POPNULL

@PUSHI 15
@IF_INRANGE_VA Var_One 10
  @PRT "FAIL IF_INRANGE_VA false (above)" @PRTNL
@ELSE
  @PRT "PASS IF_INRANGE_VA false (above)" @PRTNL
@ENDIF
@POPNULL


# === TEST IF_INRANGE_VV ===
@PUSHI Var_Five
@IF_INRANGE_VV Var_One Var_Large
  @PRT "PASS IF_INRANGE_VV true" @PRTNL
@ELSE
  @PRT "FAIL IF_INRANGE_VV true" @PRTNL
@ENDIF
@POPNULL

@PUSHI 15
@IF_INRANGE_VV Var_One Var_Large
  @PRT "FAIL IF_INRANGE_VV false (above)" @PRTNL
@ELSE
  @PRT "PASS IF_INRANGE_VV false (above)" @PRTNL
@ENDIF
@POPNULL

@PRT "END IF TESTS" @PRTNL
@PRTNL

@END

